#!/bin/bash
#$ -S /bin/bash
#$ -m a
#$ -M leon@dcs.shef.ac.uk
#$ -o /home/ac1ld/ci4bd-ner.log
#$ -t 1:5
#$ -N ci4bd-ner
#$ -l h_rt=10:00:00

module load apps/python-conda
source activate ci4bd

cd entity-recognition
./run_tagger.py  -f /fastdata/ac1ld/reddit/reddit/thinned-json/thinned$SGE_TASK_ID.json --model reddit.model.100.gha250m2k.4cat -c brown_paths/gha.250M-c2000.paths --json --json-text body --stdout > /data/ac1ld/reddit/annotated/annotated$SGE_TASK_ID.json
